package com.lightswitch.ramdom.smeta.protocol;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

public final class Protocol {
  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_Command_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_Command_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_Command_ValuesEntry_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_Command_ValuesEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.FileDescriptor
          descriptor;

  static {
    java.lang.String[] descriptorData = {
            "\n\016protocol.proto\"\201\001\n\007Command\022$\n\006values\030\001" +
                    " \003(\0132\024.Command.ValuesEntry\022\016\n\006client\030\002 \001" +
                    "(\t\022\021\n\ttimestamp\030\003 \001(\004\032-\n\013ValuesEntry\022\013\n\003" +
                    "key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[]{
                    });
    internal_static_Command_descriptor =
            getDescriptor().getMessageTypes().get(0);
    internal_static_Command_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_Command_descriptor,
            new java.lang.String[]{"Values", "Client", "Timestamp",});
    internal_static_Command_ValuesEntry_descriptor =
            internal_static_Command_descriptor.getNestedTypes().get(0);
    internal_static_Command_ValuesEntry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_Command_ValuesEntry_descriptor,
            new java.lang.String[]{"Key", "Value",});
  }

  private Protocol() {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }

  public interface CommandOrBuilder extends
          // @@protoc_insertion_point(interface_extends:Command)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, string&gt; values = 1;</code>
     */
    int getValuesCount();

    /**
     * <code>map&lt;string, string&gt; values = 1;</code>
     */
    boolean containsValues(
            java.lang.String key);

    /**
     * Use {@link #getValuesMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getValues();

    /**
     * <code>map&lt;string, string&gt; values = 1;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getValuesMap();

    /**
     * <code>map&lt;string, string&gt; values = 1;</code>
     */

    java.lang.String getValuesOrDefault(
            java.lang.String key,
            java.lang.String defaultValue);

    /**
     * <code>map&lt;string, string&gt; values = 1;</code>
     */

    java.lang.String getValuesOrThrow(
            java.lang.String key);

    /**
     * <code>string client = 2;</code>
     *
     * @return The client.
     */
    java.lang.String getClient();

    /**
     * <code>string client = 2;</code>
     *
     * @return The bytes for client.
     */
    com.google.protobuf.ByteString
    getClientBytes();

    /**
     * <code>uint64 timestamp = 3;</code>
     *
     * @return The timestamp.
     */
    long getTimestamp();
  }

  /**
   * Protobuf type {@code Command}
   */
  public static final class Command extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:Command)
          CommandOrBuilder {
    public static final int VALUES_FIELD_NUMBER = 1;
    public static final int CLIENT_FIELD_NUMBER = 2;
    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:Command)
    private static final Protocol.Command DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<Command>
            PARSER = new com.google.protobuf.AbstractParser<Command>() {
      @java.lang.Override
      public Command parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return new Command(input, extensionRegistry);
      }
    };

    static {
      DEFAULT_INSTANCE = new Protocol.Command();
    }

    private com.google.protobuf.MapField<
            java.lang.String, java.lang.String> values_;
    private volatile java.lang.Object client_;
    private long timestamp_;
    private byte memoizedIsInitialized = -1;

    // Use Command.newBuilder() to construct.
    private Command(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private Command() {
      client_ = "";
    }

    private Command(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                values_ = com.google.protobuf.MapField.newMapField(
                        ValuesDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                      values__ = input.readMessage(
                      ValuesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              values_.getMutableMap().put(
                      values__.getKey(), values__.getValue());
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              client_ = s;
              break;
            }
            case 24: {

              timestamp_ = input.readUInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                      input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return Protocol.internal_static_Command_descriptor;
    }

    public static Protocol.Command parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static Protocol.Command parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Protocol.Command parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static Protocol.Command parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Protocol.Command parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static Protocol.Command parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Protocol.Command parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }

    public static Protocol.Command parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Protocol.Command parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }

    public static Protocol.Command parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static Protocol.Command parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }

    public static Protocol.Command parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(Protocol.Command prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static Protocol.Command getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<Command> parser() {
      return PARSER;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
      return new Command();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
            int number) {
      switch (number) {
        case 1:
          return internalGetValues();
        default:
          throw new RuntimeException(
                  "Invalid map field number: " + number);
      }
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return Protocol.internal_static_Command_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      Protocol.Command.class, Protocol.Command.Builder.class);
    }

    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetValues() {
      if (values_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
                ValuesDefaultEntryHolder.defaultEntry);
      }
      return values_;
    }

    public int getValuesCount() {
      return internalGetValues().getMap().size();
    }

    /**
     * <code>map&lt;string, string&gt; values = 1;</code>
     */

    @java.lang.Override
    public boolean containsValues(
            java.lang.String key) {
      if (key == null) {
        throw new java.lang.NullPointerException();
      }
      return internalGetValues().getMap().containsKey(key);
    }

    /**
     * Use {@link #getValuesMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getValues() {
      return getValuesMap();
    }

    /**
     * <code>map&lt;string, string&gt; values = 1;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getValuesMap() {
      return internalGetValues().getMap();
    }

    /**
     * <code>map&lt;string, string&gt; values = 1;</code>
     */
    @java.lang.Override

    public java.lang.String getValuesOrDefault(
            java.lang.String key,
            java.lang.String defaultValue) {
      if (key == null) {
        throw new java.lang.NullPointerException();
      }
      java.util.Map<java.lang.String, java.lang.String> map =
              internalGetValues().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }

    /**
     * <code>map&lt;string, string&gt; values = 1;</code>
     */
    @java.lang.Override

    public java.lang.String getValuesOrThrow(
            java.lang.String key) {
      if (key == null) {
        throw new java.lang.NullPointerException();
      }
      java.util.Map<java.lang.String, java.lang.String> map =
              internalGetValues().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    /**
     * <code>string client = 2;</code>
     *
     * @return The client.
     */
    @java.lang.Override
    public java.lang.String getClient() {
      java.lang.Object ref = client_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        client_ = s;
        return s;
      }
    }

    /**
     * <code>string client = 2;</code>
     *
     * @return The bytes for client.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getClientBytes() {
      java.lang.Object ref = client_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        client_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>uint64 timestamp = 3;</code>
     *
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
              .serializeStringMapTo(
                      output,
                      internalGetValues(),
                      ValuesDefaultEntryHolder.defaultEntry,
                      1);
      if (!getClientBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, client_);
      }
      if (timestamp_ != 0L) {
        output.writeUInt64(3, timestamp_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
              : internalGetValues().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                values__ = ValuesDefaultEntryHolder.defaultEntry.newBuilderForType()
                .setKey(entry.getKey())
                .setValue(entry.getValue())
                .build();
        size += com.google.protobuf.CodedOutputStream
                .computeMessageSize(1, values__);
      }
      if (!getClientBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, client_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
                .computeUInt64Size(3, timestamp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof Protocol.Command)) {
        return super.equals(obj);
      }
      Protocol.Command other = (Protocol.Command) obj;

      if (!internalGetValues().equals(
              other.internalGetValues())) return false;
      if (!getClient()
              .equals(other.getClient())) return false;
      if (getTimestamp()
              != other.getTimestamp()) return false;
      return unknownFields.equals(other.unknownFields);
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetValues().getMap().isEmpty()) {
        hash = (37 * hash) + VALUES_FIELD_NUMBER;
        hash = (53 * hash) + internalGetValues().hashCode();
      }
      hash = (37 * hash) + CLIENT_FIELD_NUMBER;
      hash = (53 * hash) + getClient().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getTimestamp());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Command> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Protocol.Command getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

    private static final class ValuesDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
              java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
                      .newDefaultInstance(
                              Protocol.internal_static_Command_ValuesEntry_descriptor,
                              com.google.protobuf.WireFormat.FieldType.STRING,
                              "",
                              com.google.protobuf.WireFormat.FieldType.STRING,
                              "");
    }

    /**
     * Protobuf type {@code Command}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:Command)
            Protocol.CommandOrBuilder {
      private int bitField0_;
      private com.google.protobuf.MapField<
              java.lang.String, java.lang.String> values_;
      private java.lang.Object client_ = "";
      private long timestamp_;

      // Construct using Protocol.Command.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return Protocol.internal_static_Command_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
              int number) {
        switch (number) {
          case 1:
            return internalGetValues();
          default:
            throw new RuntimeException(
                    "Invalid map field number: " + number);
        }
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
              int number) {
        switch (number) {
          case 1:
            return internalGetMutableValues();
          default:
            throw new RuntimeException(
                    "Invalid map field number: " + number);
        }
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return Protocol.internal_static_Command_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        Protocol.Command.class, Protocol.Command.Builder.class);
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        internalGetMutableValues().clear();
        client_ = "";

        timestamp_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return Protocol.internal_static_Command_descriptor;
      }

      @java.lang.Override
      public Protocol.Command getDefaultInstanceForType() {
        return Protocol.Command.getDefaultInstance();
      }

      @java.lang.Override
      public Protocol.Command build() {
        Protocol.Command result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Protocol.Command buildPartial() {
        Protocol.Command result = new Protocol.Command(this);
        int from_bitField0_ = bitField0_;
        result.values_ = internalGetValues();
        result.values_.makeImmutable();
        result.client_ = client_;
        result.timestamp_ = timestamp_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }

      @java.lang.Override
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Protocol.Command) {
          return mergeFrom((Protocol.Command) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Protocol.Command other) {
        if (other == Protocol.Command.getDefaultInstance()) return this;
        internalGetMutableValues().mergeFrom(
                other.internalGetValues());
        if (!other.getClient().isEmpty()) {
          client_ = other.client_;
          onChanged();
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        Protocol.Command parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Protocol.Command) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetValues() {
        if (values_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
                  ValuesDefaultEntryHolder.defaultEntry);
        }
        return values_;
      }

      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableValues() {
        onChanged();
        if (values_ == null) {
          values_ = com.google.protobuf.MapField.newMapField(
                  ValuesDefaultEntryHolder.defaultEntry);
        }
        if (!values_.isMutable()) {
          values_ = values_.copy();
        }
        return values_;
      }

      public int getValuesCount() {
        return internalGetValues().getMap().size();
      }

      /**
       * <code>map&lt;string, string&gt; values = 1;</code>
       */

      @java.lang.Override
      public boolean containsValues(
              java.lang.String key) {
        if (key == null) {
          throw new java.lang.NullPointerException();
        }
        return internalGetValues().getMap().containsKey(key);
      }

      /**
       * Use {@link #getValuesMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getValues() {
        return getValuesMap();
      }

      /**
       * <code>map&lt;string, string&gt; values = 1;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, java.lang.String> getValuesMap() {
        return internalGetValues().getMap();
      }

      /**
       * <code>map&lt;string, string&gt; values = 1;</code>
       */
      @java.lang.Override

      public java.lang.String getValuesOrDefault(
              java.lang.String key,
              java.lang.String defaultValue) {
        if (key == null) {
          throw new java.lang.NullPointerException();
        }
        java.util.Map<java.lang.String, java.lang.String> map =
                internalGetValues().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }

      /**
       * <code>map&lt;string, string&gt; values = 1;</code>
       */
      @java.lang.Override

      public java.lang.String getValuesOrThrow(
              java.lang.String key) {
        if (key == null) {
          throw new java.lang.NullPointerException();
        }
        java.util.Map<java.lang.String, java.lang.String> map =
                internalGetValues().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearValues() {
        internalGetMutableValues().getMutableMap()
                .clear();
        return this;
      }

      /**
       * <code>map&lt;string, string&gt; values = 1;</code>
       */

      public Builder removeValues(
              java.lang.String key) {
        if (key == null) {
          throw new java.lang.NullPointerException();
        }
        internalGetMutableValues().getMutableMap()
                .remove(key);
        return this;
      }

      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableValues() {
        return internalGetMutableValues().getMutableMap();
      }

      /**
       * <code>map&lt;string, string&gt; values = 1;</code>
       */
      public Builder putValues(
              java.lang.String key,
              java.lang.String value) {
        if (key == null) {
          throw new java.lang.NullPointerException();
        }
        if (value == null) {
          throw new java.lang.NullPointerException();
        }
        internalGetMutableValues().getMutableMap()
                .put(key, value);
        return this;
      }

      /**
       * <code>map&lt;string, string&gt; values = 1;</code>
       */

      public Builder putAllValues(
              java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableValues().getMutableMap()
                .putAll(values);
        return this;
      }

      /**
       * <code>string client = 2;</code>
       *
       * @return The client.
       */
      public java.lang.String getClient() {
        java.lang.Object ref = client_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          client_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>string client = 2;</code>
       *
       * @param value The client to set.
       * @return This builder for chaining.
       */
      public Builder setClient(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        client_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string client = 2;</code>
       *
       * @return The bytes for client.
       */
      public com.google.protobuf.ByteString
      getClientBytes() {
        java.lang.Object ref = client_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          client_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>string client = 2;</code>
       *
       * @param value The bytes for client to set.
       * @return This builder for chaining.
       */
      public Builder setClientBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        client_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string client = 2;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearClient() {

        client_ = getDefaultInstance().getClient();
        onChanged();
        return this;
      }

      /**
       * <code>uint64 timestamp = 3;</code>
       *
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }

      /**
       * <code>uint64 timestamp = 3;</code>
       *
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {

        timestamp_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>uint64 timestamp = 3;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {

        timestamp_ = 0L;
        onChanged();
        return this;
      }

      @java.lang.Override
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Command)
    }

  }

  // @@protoc_insertion_point(outer_class_scope)
}
